package mc.sbm.simphonycloud.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ElementMenuAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertElementMenuAllPropertiesEquals(ElementMenu expected, ElementMenu actual) {
        assertElementMenuAutoGeneratedPropertiesEquals(expected, actual);
        assertElementMenuAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertElementMenuAllUpdatablePropertiesEquals(ElementMenu expected, ElementMenu actual) {
        assertElementMenuUpdatableFieldsEquals(expected, actual);
        assertElementMenuUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertElementMenuAutoGeneratedPropertiesEquals(ElementMenu expected, ElementMenu actual) {
        assertThat(actual)
            .as("Verify ElementMenu auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertElementMenuUpdatableFieldsEquals(ElementMenu expected, ElementMenu actual) {
        assertThat(actual)
            .as("Verify ElementMenu relevant properties")
            .satisfies(a -> assertThat(a.getMasterId()).as("check masterId").isEqualTo(expected.getMasterId()))
            .satisfies(a -> assertThat(a.getNom()).as("check nom").isEqualTo(expected.getNom()))
            .satisfies(a -> assertThat(a.getNomCourt()).as("check nomCourt").isEqualTo(expected.getNomCourt()))
            .satisfies(a -> assertThat(a.getFamilyGroupRef()).as("check familyGroupRef").isEqualTo(expected.getFamilyGroupRef()))
            .satisfies(a -> assertThat(a.getPrix()).as("check prix").isEqualTo(expected.getPrix()))
            .satisfies(a -> assertThat(a.getMenuRef()).as("check menuRef").isEqualTo(expected.getMenuRef()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertElementMenuUpdatableRelationshipsEquals(ElementMenu expected, ElementMenu actual) {
        // empty method
    }
}
