package mc.sbm.simphonycloud.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class FamilyGroupCnCAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFamilyGroupCnCAllPropertiesEquals(FamilyGroupCnC expected, FamilyGroupCnC actual) {
        assertFamilyGroupCnCAutoGeneratedPropertiesEquals(expected, actual);
        assertFamilyGroupCnCAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFamilyGroupCnCAllUpdatablePropertiesEquals(FamilyGroupCnC expected, FamilyGroupCnC actual) {
        assertFamilyGroupCnCUpdatableFieldsEquals(expected, actual);
        assertFamilyGroupCnCUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFamilyGroupCnCAutoGeneratedPropertiesEquals(FamilyGroupCnC expected, FamilyGroupCnC actual) {
        assertThat(actual)
            .as("Verify FamilyGroupCnC auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFamilyGroupCnCUpdatableFieldsEquals(FamilyGroupCnC expected, FamilyGroupCnC actual) {
        assertThat(actual)
            .as("Verify FamilyGroupCnC relevant properties")
            .satisfies(a -> assertThat(a.getNom()).as("check nom").isEqualTo(expected.getNom()))
            .satisfies(a -> assertThat(a.getNomCourt()).as("check nomCourt").isEqualTo(expected.getNomCourt()))
            .satisfies(a -> assertThat(a.getMajorGroupRef()).as("check majorGroupRef").isEqualTo(expected.getMajorGroupRef()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFamilyGroupCnCUpdatableRelationshipsEquals(FamilyGroupCnC expected, FamilyGroupCnC actual) {
        // empty method
    }
}
