package mc.sbm.simphonycloud.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class FamilyGroupAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFamilyGroupAllPropertiesEquals(FamilyGroup expected, FamilyGroup actual) {
        assertFamilyGroupAutoGeneratedPropertiesEquals(expected, actual);
        assertFamilyGroupAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFamilyGroupAllUpdatablePropertiesEquals(FamilyGroup expected, FamilyGroup actual) {
        assertFamilyGroupUpdatableFieldsEquals(expected, actual);
        assertFamilyGroupUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFamilyGroupAutoGeneratedPropertiesEquals(FamilyGroup expected, FamilyGroup actual) {
        assertThat(actual)
            .as("Verify FamilyGroup auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFamilyGroupUpdatableFieldsEquals(FamilyGroup expected, FamilyGroup actual) {
        assertThat(actual)
            .as("Verify FamilyGroup relevant properties")
            .satisfies(a -> assertThat(a.getNom()).as("check nom").isEqualTo(expected.getNom()))
            .satisfies(a -> assertThat(a.getNomCourt()).as("check nomCourt").isEqualTo(expected.getNomCourt()))
            .satisfies(a -> assertThat(a.getMajorGroupRef()).as("check majorGroupRef").isEqualTo(expected.getMajorGroupRef()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFamilyGroupUpdatableRelationshipsEquals(FamilyGroup expected, FamilyGroup actual) {
        // empty method
    }
}
