package mc.sbm.simphonycloud.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class HierarchieAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHierarchieAllPropertiesEquals(Hierarchie expected, Hierarchie actual) {
        assertHierarchieAutoGeneratedPropertiesEquals(expected, actual);
        assertHierarchieAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHierarchieAllUpdatablePropertiesEquals(Hierarchie expected, Hierarchie actual) {
        assertHierarchieUpdatableFieldsEquals(expected, actual);
        assertHierarchieUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHierarchieAutoGeneratedPropertiesEquals(Hierarchie expected, Hierarchie actual) {
        assertThat(actual)
            .as("Verify Hierarchie auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHierarchieUpdatableFieldsEquals(Hierarchie expected, Hierarchie actual) {
        assertThat(actual)
            .as("Verify Hierarchie relevant properties")
            .satisfies(a -> assertThat(a.getNom()).as("check nom").isEqualTo(expected.getNom()))
            .satisfies(a -> assertThat(a.getParentHierId()).as("check parentHierId").isEqualTo(expected.getParentHierId()))
            .satisfies(a -> assertThat(a.getUnitId()).as("check unitId").isEqualTo(expected.getUnitId()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHierarchieUpdatableRelationshipsEquals(Hierarchie expected, Hierarchie actual) {
        // empty method
    }
}
