package mc.sbm.simphonycloud.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class HierarchieCnCAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHierarchieCnCAllPropertiesEquals(HierarchieCnC expected, HierarchieCnC actual) {
        assertHierarchieCnCAutoGeneratedPropertiesEquals(expected, actual);
        assertHierarchieCnCAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHierarchieCnCAllUpdatablePropertiesEquals(HierarchieCnC expected, HierarchieCnC actual) {
        assertHierarchieCnCUpdatableFieldsEquals(expected, actual);
        assertHierarchieCnCUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHierarchieCnCAutoGeneratedPropertiesEquals(HierarchieCnC expected, HierarchieCnC actual) {
        assertThat(actual)
            .as("Verify HierarchieCnC auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHierarchieCnCUpdatableFieldsEquals(HierarchieCnC expected, HierarchieCnC actual) {
        assertThat(actual)
            .as("Verify HierarchieCnC relevant properties")
            .satisfies(a -> assertThat(a.getNom()).as("check nom").isEqualTo(expected.getNom()))
            .satisfies(a -> assertThat(a.getParentHierId()).as("check parentHierId").isEqualTo(expected.getParentHierId()))
            .satisfies(a -> assertThat(a.getUnitId()).as("check unitId").isEqualTo(expected.getUnitId()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHierarchieCnCUpdatableRelationshipsEquals(HierarchieCnC expected, HierarchieCnC actual) {
        // empty method
    }
}
