package mc.sbm.simphonycloud.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MajorGroupCnCAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMajorGroupCnCAllPropertiesEquals(MajorGroupCnC expected, MajorGroupCnC actual) {
        assertMajorGroupCnCAutoGeneratedPropertiesEquals(expected, actual);
        assertMajorGroupCnCAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMajorGroupCnCAllUpdatablePropertiesEquals(MajorGroupCnC expected, MajorGroupCnC actual) {
        assertMajorGroupCnCUpdatableFieldsEquals(expected, actual);
        assertMajorGroupCnCUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMajorGroupCnCAutoGeneratedPropertiesEquals(MajorGroupCnC expected, MajorGroupCnC actual) {
        assertThat(actual)
            .as("Verify MajorGroupCnC auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMajorGroupCnCUpdatableFieldsEquals(MajorGroupCnC expected, MajorGroupCnC actual) {
        assertThat(actual)
            .as("Verify MajorGroupCnC relevant properties")
            .satisfies(a -> assertThat(a.getNom()).as("check nom").isEqualTo(expected.getNom()))
            .satisfies(a -> assertThat(a.getNomCourt()).as("check nomCourt").isEqualTo(expected.getNomCourt()))
            .satisfies(a -> assertThat(a.getPointDeVenteRef()).as("check pointDeVenteRef").isEqualTo(expected.getPointDeVenteRef()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMajorGroupCnCUpdatableRelationshipsEquals(MajorGroupCnC expected, MajorGroupCnC actual) {
        // empty method
    }
}
