package mc.sbm.simphonycloud.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MajorGroupAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMajorGroupAllPropertiesEquals(MajorGroup expected, MajorGroup actual) {
        assertMajorGroupAutoGeneratedPropertiesEquals(expected, actual);
        assertMajorGroupAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMajorGroupAllUpdatablePropertiesEquals(MajorGroup expected, MajorGroup actual) {
        assertMajorGroupUpdatableFieldsEquals(expected, actual);
        assertMajorGroupUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMajorGroupAutoGeneratedPropertiesEquals(MajorGroup expected, MajorGroup actual) {
        assertThat(actual)
            .as("Verify MajorGroup auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMajorGroupUpdatableFieldsEquals(MajorGroup expected, MajorGroup actual) {
        assertThat(actual)
            .as("Verify MajorGroup relevant properties")
            .satisfies(a -> assertThat(a.getNom()).as("check nom").isEqualTo(expected.getNom()))
            .satisfies(a -> assertThat(a.getNomCourt()).as("check nomCourt").isEqualTo(expected.getNomCourt()))
            .satisfies(a -> assertThat(a.getPointDeVenteRef()).as("check pointDeVenteRef").isEqualTo(expected.getPointDeVenteRef()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMajorGroupUpdatableRelationshipsEquals(MajorGroup expected, MajorGroup actual) {
        // empty method
    }
}
