package mc.sbm.simphonycloud.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MenuItemPricesCnCAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMenuItemPricesCnCAllPropertiesEquals(MenuItemPricesCnC expected, MenuItemPricesCnC actual) {
        assertMenuItemPricesCnCAutoGeneratedPropertiesEquals(expected, actual);
        assertMenuItemPricesCnCAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMenuItemPricesCnCAllUpdatablePropertiesEquals(MenuItemPricesCnC expected, MenuItemPricesCnC actual) {
        assertMenuItemPricesCnCUpdatableFieldsEquals(expected, actual);
        assertMenuItemPricesCnCUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMenuItemPricesCnCAutoGeneratedPropertiesEquals(MenuItemPricesCnC expected, MenuItemPricesCnC actual) {
        assertThat(actual)
            .as("Verify MenuItemPricesCnC auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMenuItemPricesCnCUpdatableFieldsEquals(MenuItemPricesCnC expected, MenuItemPricesCnC actual) {
        assertThat(actual)
            .as("Verify MenuItemPricesCnC relevant properties")
            .satisfies(a -> assertThat(a.getHierUnitId()).as("check hierUnitId").isEqualTo(expected.getHierUnitId()))
            .satisfies(a -> assertThat(a.getMenuItemPriceId()).as("check menuItemPriceId").isEqualTo(expected.getMenuItemPriceId()))
            .satisfies(a -> assertThat(a.getMenuItemMasterId()).as("check menuItemMasterId").isEqualTo(expected.getMenuItemMasterId()))
            .satisfies(a ->
                assertThat(a.getMenuItemMasterObjNum()).as("check menuItemMasterObjNum").isEqualTo(expected.getMenuItemMasterObjNum())
            )
            .satisfies(a ->
                assertThat(a.getMenuItemDefinitionId()).as("check menuItemDefinitionId").isEqualTo(expected.getMenuItemDefinitionId())
            )
            .satisfies(a -> assertThat(a.getDefSequenceNum()).as("check defSequenceNum").isEqualTo(expected.getDefSequenceNum()))
            .satisfies(a -> assertThat(a.getExternalReference1()).as("check externalReference1").isEqualTo(expected.getExternalReference1())
            )
            .satisfies(a -> assertThat(a.getExternalReference2()).as("check externalReference2").isEqualTo(expected.getExternalReference2())
            )
            .satisfies(a -> assertThat(a.getPriceSequenceNum()).as("check priceSequenceNum").isEqualTo(expected.getPriceSequenceNum()))
            .satisfies(a -> assertThat(a.getActiveOnMenuLevel()).as("check activeOnMenuLevel").isEqualTo(expected.getActiveOnMenuLevel()))
            .satisfies(a ->
                assertThat(a.getEffectivityGroupObjNum()).as("check effectivityGroupObjNum").isEqualTo(expected.getEffectivityGroupObjNum())
            )
            .satisfies(a -> assertThat(a.getPrepCost()).as("check prepCost").isEqualTo(expected.getPrepCost()))
            .satisfies(a -> assertThat(a.getPrice()).as("check price").isEqualTo(expected.getPrice()))
            .satisfies(a -> assertThat(a.getOptions()).as("check options").isEqualTo(expected.getOptions()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMenuItemPricesCnCUpdatableRelationshipsEquals(MenuItemPricesCnC expected, MenuItemPricesCnC actual) {
        // empty method
    }
}
