package mc.sbm.simphonycloud.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ModePaiementBIAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertModePaiementBIAllPropertiesEquals(ModePaiementBI expected, ModePaiementBI actual) {
        assertModePaiementBIAutoGeneratedPropertiesEquals(expected, actual);
        assertModePaiementBIAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertModePaiementBIAllUpdatablePropertiesEquals(ModePaiementBI expected, ModePaiementBI actual) {
        assertModePaiementBIUpdatableFieldsEquals(expected, actual);
        assertModePaiementBIUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertModePaiementBIAutoGeneratedPropertiesEquals(ModePaiementBI expected, ModePaiementBI actual) {
        assertThat(actual)
            .as("Verify ModePaiementBI auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertModePaiementBIUpdatableFieldsEquals(ModePaiementBI expected, ModePaiementBI actual) {
        assertThat(actual)
            .as("Verify ModePaiementBI relevant properties")
            .satisfies(a -> assertThat(a.getLocRef()).as("check locRef").isEqualTo(expected.getLocRef()))
            .satisfies(a -> assertThat(a.getNum()).as("check num").isEqualTo(expected.getNum()))
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getType()).as("check type").isEqualTo(expected.getType()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertModePaiementBIUpdatableRelationshipsEquals(ModePaiementBI expected, ModePaiementBI actual) {
        // empty method
    }
}
