package mc.sbm.simphonycloud.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class OrderChannelAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrderChannelAllPropertiesEquals(OrderChannel expected, OrderChannel actual) {
        assertOrderChannelAutoGeneratedPropertiesEquals(expected, actual);
        assertOrderChannelAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrderChannelAllUpdatablePropertiesEquals(OrderChannel expected, OrderChannel actual) {
        assertOrderChannelUpdatableFieldsEquals(expected, actual);
        assertOrderChannelUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrderChannelAutoGeneratedPropertiesEquals(OrderChannel expected, OrderChannel actual) {
        assertThat(actual)
            .as("Verify OrderChannel auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrderChannelUpdatableFieldsEquals(OrderChannel expected, OrderChannel actual) {
        assertThat(actual)
            .as("Verify OrderChannel relevant properties")
            .satisfies(a -> assertThat(a.getNum()).as("check num").isEqualTo(expected.getNum()))
            .satisfies(a -> assertThat(a.getLocRef()).as("check locRef").isEqualTo(expected.getLocRef()))
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getMstrNum()).as("check mstrNum").isEqualTo(expected.getMstrNum()))
            .satisfies(a -> assertThat(a.getMstrName()).as("check mstrName").isEqualTo(expected.getMstrName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrderChannelUpdatableRelationshipsEquals(OrderChannel expected, OrderChannel actual) {
        // empty method
    }
}
