package mc.sbm.simphonycloud.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class OrderTypeBIAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrderTypeBIAllPropertiesEquals(OrderTypeBI expected, OrderTypeBI actual) {
        assertOrderTypeBIAutoGeneratedPropertiesEquals(expected, actual);
        assertOrderTypeBIAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrderTypeBIAllUpdatablePropertiesEquals(OrderTypeBI expected, OrderTypeBI actual) {
        assertOrderTypeBIUpdatableFieldsEquals(expected, actual);
        assertOrderTypeBIUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrderTypeBIAutoGeneratedPropertiesEquals(OrderTypeBI expected, OrderTypeBI actual) {
        assertThat(actual)
            .as("Verify OrderTypeBI auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrderTypeBIUpdatableFieldsEquals(OrderTypeBI expected, OrderTypeBI actual) {
        assertThat(actual)
            .as("Verify OrderTypeBI relevant properties")
            .satisfies(a -> assertThat(a.getNum()).as("check num").isEqualTo(expected.getNum()))
            .satisfies(a -> assertThat(a.getLocRef()).as("check locRef").isEqualTo(expected.getLocRef()))
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getMstrNum()).as("check mstrNum").isEqualTo(expected.getMstrNum()))
            .satisfies(a -> assertThat(a.getMstrName()).as("check mstrName").isEqualTo(expected.getMstrName()))
            .satisfies(a -> assertThat(a.getCatGrpHierName1()).as("check catGrpHierName1").isEqualTo(expected.getCatGrpHierName1()))
            .satisfies(a -> assertThat(a.getCatGrpName1()).as("check catGrpName1").isEqualTo(expected.getCatGrpName1()))
            .satisfies(a -> assertThat(a.getCatGrpHierName2()).as("check catGrpHierName2").isEqualTo(expected.getCatGrpHierName2()))
            .satisfies(a -> assertThat(a.getCatGrpName2()).as("check catGrpName2").isEqualTo(expected.getCatGrpName2()))
            .satisfies(a -> assertThat(a.getCatGrpHierName3()).as("check catGrpHierName3").isEqualTo(expected.getCatGrpHierName3()))
            .satisfies(a -> assertThat(a.getCatGrpName3()).as("check catGrpName3").isEqualTo(expected.getCatGrpName3()))
            .satisfies(a -> assertThat(a.getCatGrpHierName4()).as("check catGrpHierName4").isEqualTo(expected.getCatGrpHierName4()))
            .satisfies(a -> assertThat(a.getCatGrpName4()).as("check catGrpName4").isEqualTo(expected.getCatGrpName4()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrderTypeBIUpdatableRelationshipsEquals(OrderTypeBI expected, OrderTypeBI actual) {
        // empty method
    }
}
