package mc.sbm.simphonycloud.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SocieteAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSocieteAllPropertiesEquals(Societe expected, Societe actual) {
        assertSocieteAutoGeneratedPropertiesEquals(expected, actual);
        assertSocieteAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSocieteAllUpdatablePropertiesEquals(Societe expected, Societe actual) {
        assertSocieteUpdatableFieldsEquals(expected, actual);
        assertSocieteUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSocieteAutoGeneratedPropertiesEquals(Societe expected, Societe actual) {
        assertThat(actual)
            .as("Verify Societe auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSocieteUpdatableFieldsEquals(Societe expected, Societe actual) {
        assertThat(actual)
            .as("Verify Societe relevant properties")
            .satisfies(a -> assertThat(a.getNom()).as("check nom").isEqualTo(expected.getNom()))
            .satisfies(a -> assertThat(a.getNomCourt()).as("check nomCourt").isEqualTo(expected.getNomCourt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSocieteUpdatableRelationshipsEquals(Societe expected, Societe actual) {
        // empty method
    }
}
