package mc.sbm.simphonycloud.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TaxeBIAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTaxeBIAllPropertiesEquals(TaxeBI expected, TaxeBI actual) {
        assertTaxeBIAutoGeneratedPropertiesEquals(expected, actual);
        assertTaxeBIAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTaxeBIAllUpdatablePropertiesEquals(TaxeBI expected, TaxeBI actual) {
        assertTaxeBIUpdatableFieldsEquals(expected, actual);
        assertTaxeBIUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTaxeBIAutoGeneratedPropertiesEquals(TaxeBI expected, TaxeBI actual) {
        assertThat(actual)
            .as("Verify TaxeBI auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTaxeBIUpdatableFieldsEquals(TaxeBI expected, TaxeBI actual) {
        assertThat(actual)
            .as("Verify TaxeBI relevant properties")
            .satisfies(a -> assertThat(a.getLocRef()).as("check locRef").isEqualTo(expected.getLocRef()))
            .satisfies(a -> assertThat(a.getNum()).as("check num").isEqualTo(expected.getNum()))
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getType()).as("check type").isEqualTo(expected.getType()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTaxeBIUpdatableRelationshipsEquals(TaxeBI expected, TaxeBI actual) {
        // empty method
    }
}
